"""drop_storage_path_checksum

Revision ID: 0132c6a5422e
Revises: 6d3183eda0be
Create Date: 2026-01-28 22:41:34.499765
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0132c6a5422e'
down_revision = '6d3183eda0be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'checksum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('checksum', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('storage_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
