"""init

Revision ID: 0746f98ddb79
Revises: 0921dc485789
Create Date: 2026-01-28 22:08:51.950078
"""

# revision identifiers, used by Alembic.
revision = '0746f98ddb79'
down_revision = '0921dc485789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
