"""init

Revision ID: 0921dc485789
Revises:
Create Date: 2026-01-28 22:08:13.618773
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0921dc485789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('correspondent_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('document_date', sa.String(length=32), nullable=True),
    sa.Column('created', sa.String(length=32), nullable=True),
    sa.Column('modified', sa.String(length=64), nullable=True),
    sa.Column('added', sa.String(length=64), nullable=True),
    sa.Column('archive_serial_number', sa.Integer(), nullable=True),
    sa.Column('original_file_name', sa.String(length=512), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_can_change', sa.Boolean(), nullable=True),
    sa.Column('is_shared_by_requester', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('document_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(length=128), nullable=True),
    sa.Column('user_first_name', sa.String(length=128), nullable=True),
    sa.Column('user_last_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_notes_document_id'), 'document_notes', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_notes_id'), 'document_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_notes_id'), table_name='document_notes')
    op.drop_index(op.f('ix_document_notes_document_id'), table_name='document_notes')
    op.drop_table('document_notes')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
