"""add_core_metadata_tables

Revision ID: 6d3183eda0be
Revises: f23ae6e45f05
Create Date: 2026-01-28 22:24:59.599819
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3183eda0be'
down_revision = 'f23ae6e45f05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('matching_algorithm', sa.String(length=64), nullable=True),
    sa.Column('is_insensitive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correspondents_id'), 'correspondents', ['id'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('matching_algorithm', sa.String(length=64), nullable=True),
    sa.Column('is_insensitive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('is_inbox_tag', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('matching_algorithm', sa.String(length=64), nullable=True),
    sa.Column('is_insensitive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_foreign_key(None, 'documents', 'correspondents', ['correspondent_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'document_types', ['document_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_correspondents_id'), table_name='correspondents')
    op.drop_table('correspondents')
    # ### end Alembic commands ###
