"""add_cancel_requested

Revision ID: 734a3748aa6a
Revises: e17c5670eb63
Create Date: 2026-01-28 23:26:03.275000
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '734a3748aa6a'
down_revision = 'e17c5670eb63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_state', sa.Column('cancel_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_state', 'cancel_requested')
    # ### end Alembic commands ###
