"""add_sync_progress

Revision ID: bb27df3fb2b5
Revises: 0132c6a5422e
Create Date: 2026-01-28 22:50:14.321968
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb27df3fb2b5'
down_revision = '0132c6a5422e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_state', sa.Column('status', sa.String(length=32), nullable=True))
    op.add_column('sync_state', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('sync_state', sa.Column('processed', sa.Integer(), nullable=True))
    op.add_column('sync_state', sa.Column('started_at', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_state', 'started_at')
    op.drop_column('sync_state', 'processed')
    op.drop_column('sync_state', 'total')
    op.drop_column('sync_state', 'status')
    # ### end Alembic commands ###
