"""add_document_embeddings

Revision ID: e17c5670eb63
Revises: bb27df3fb2b5
Create Date: 2026-01-28 23:12:09.562008
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17c5670eb63'
down_revision = 'bb27df3fb2b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedded_at', sa.String(length=64), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_embeddings')
    # ### end Alembic commands ###
