"""add_sync_state

Revision ID: f23ae6e45f05
Revises: 0746f98ddb79
Create Date: 2026-01-28 22:11:18.577964
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f23ae6e45f05'
down_revision = '0746f98ddb79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('last_synced_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    # ### end Alembic commands ###
